# Assignment on Big Data
The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load. Features consist of hourly average ambient variables Temperature (T), Ambient Pressure (AP), Relative Humidity (RH) and Exhaust Vacuum (V) to predict the net hourly electrical energy output (EP)  of the plant.

import libraries 

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import the dataset

In [13]:
file = 'Data.csv'
data = pd.read_csv(file)
X = data.iloc[:,:3].values
Y = data.iloc[:,-1].values

In [64]:
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

# Multivariate Linear Regression

In [33]:
# split the dataset btw train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 1/3, random_state = 0)

In [34]:
# Training the Simple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [37]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [43]:
# reshape test and results 
y_train = y_train.reshape(len(y_train),1)
y_test = y_test.reshape(len(y_test),1)
y_pred = y_pred.reshape(len(y_pred),1)

In [58]:
# Evaluate the model
from sklearn.metrics import r2_score
predd = regressor.predict(X_test)
print("r2 score :",r2_score(predd,y_test))

r2 score : 0.9133234359945821


# Polynomial Linear Regression


In [60]:
# training the Polynomial Linear Regression
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(4)
poly_x = poly.fit_transform(X_train)
poly.fit(poly_x,y_train)

regressor2 = LinearRegression()
regressor2.fit(poly_x, y_train)

LinearRegression()

In [62]:
pred_polynomial = regressor2.predict(poly.fit_transform(X_test))
print("r2 score :",r2_score(pred_polynomial,y_test))

r2 score : 0.9347390850372573


# Support Vector Regression

In [65]:
# test : Scale the variable
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)


scaler.fit(X_test)
X_test_scaled = scaler.transform(X_test)

In [66]:
# trainning the support vector model
from sklearn import svm

reg = svm.SVR()
reg.fit(X_train_scaled,y_train)
reg.predict(X_test_scaled)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([433.24, 459.3 , 465.94, ..., 451.86, 467.17, 456.18])

In [67]:
pred_svc = reg.predict(X_test_scaled)
print("r2 score :",r2_score(pred_svc,y_test))

r2 score : 0.9349103951112642


In [68]:
# test : Without scaling the variable
# trainning the support vector model
from sklearn import svm

reg = svm.SVR()
reg.fit(X_train,y_train)
reg.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([446.06, 453.79, 455.23, ..., 452.48, 454.67, 453.2 ])

In [69]:
pred_svc2 = reg.predict(X_test)
print("r2 score :",r2_score(pred_svc2,y_test))

r2 score : -15.089656319515672


the above implementation shows that we need to scale the variable since the values do not have the same unit

# Decision Tree

In [72]:
from sklearn import tree

clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train,y_train)
clf.predict(X_test)

array([432.67, 454.67, 466.  , ..., 453.4 , 468.87, 453.96])

In [73]:
pred_dt = clf.predict(X_test)
print("r2 score :",r2_score(pred_dt,y_test))

r2 score : 0.9176055418251277


# Random Forest

In [74]:
from sklearn.ensemble import RandomForestRegressor

reg = RandomForestRegressor(n_estimators = 10, random_state = 0)
reg.fit(X_train,y_train)
reg.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([434.48, 455.82, 464.76, ..., 453.66, 468.6 , 454.04])

In [75]:
pred_rf = reg.predict(X_test)
print("r2 score :",r2_score(pred_rf,y_test))

r2 score : 0.9535156116378418


The above model evaluation shows r-squared values for 5 regression models on the big dataset. From the above evaluation, it can be concluded that Random Forest is the best model as it has the higest r-squared score.